apiVersion: apps/v1
kind: Deployment
metadata:
  name: object-detection-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: object-detection-app
  template:
    metadata:
      labels:
        app: object-detection-app
    spec:
      containers:
      - name: object-detection-app
        image: your_dockerhub_username/object-detection-app
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: object-detection-service
spec:
  selector:
    app: object-detection-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

